# Generated by Django 3.1.2 on 2020-10-14 09:17

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
